---
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - /root/frontend/homepage/config:/app/config
      - /root/frontend/homepage/images:/app/public/images
      - /root/frontend/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      frontend:
    labels:
      traefik.enable: "true"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
      traefik.http.services.homepage.loadbalancer.server.scheme: "http"
      traefik.http.routers.homepage-http.rule: "Host(`homepage.jotamario.lat`)"
      traefik.http.routers.homepage-http.entrypoints: "web"
      traefik.http.routers.homepage-https.tls: "true"
      traefik.http.routers.homepage-https.tls.certresolver: "cloudflare"
      traefik.http.routers.homepage-https.entrypoints: "websecure"
      traefik.http.routers.homepage-https.rule: "Host(`homepage.jotamario.lat`)"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy 
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      frontend:
networks:
  frontend:
    external: true