---
volumes:
  portainer-data:
    driver: local
networks:
  backend:
    external: true
services:
  app:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4-alpine
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000 # for http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.backend.jotamario.lat`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.backend.jotamario.lat`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=backend"
    restart: unless-stopped
    networks:
      - backend